import Link from "next/link";

export default function Home() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero */}
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg flex items-center justify-center">
            <span className="text-white font-bold text-sm">PP</span>
          </div>
          <span className="text-xl font-bold text-gray-900">ProposalPilot</span>
        </div>
        <div className="flex items-center gap-2 sm:gap-4">
          <Link href="/auth/signin" className="text-gray-600 hover:text-gray-900 font-medium text-sm sm:text-base px-2 py-2">
            Sign In
          </Link>
          <Link
            href="/auth/signup"
            className="bg-blue-600 text-white px-4 sm:px-5 py-2.5 rounded-lg hover:bg-blue-700 font-medium transition text-sm sm:text-base min-h-[44px] flex items-center"
          >
            Get Started Free
          </Link>
        </div>
      </nav>

      <main>
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-20 md:py-32">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 px-4 py-1.5 rounded-full text-sm font-medium mb-6">
              ✨ AI-Powered Proposal Generation
            </div>
            <h1 className="text-3xl sm:text-5xl md:text-7xl font-bold text-gray-900 tracking-tight leading-tight">
              Win more clients with{" "}
              <span className="gradient-text">
                stunning proposals
              </span>
            </h1>
            <p className="mt-4 sm:mt-6 text-base sm:text-xl text-gray-600 max-w-2xl mx-auto">
              Describe your project in plain English and let AI generate professional,
              detailed proposals in seconds. Close deals faster.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/auth/signup"
                className="bg-blue-600 text-white px-6 sm:px-8 py-4 rounded-xl text-base sm:text-lg font-semibold hover:bg-blue-700 transition shadow-lg shadow-blue-600/25 min-h-[48px] flex items-center justify-center"
              >
                Start Creating Proposals →
              </Link>
              <Link
                href="/auth/signin"
                className="bg-gray-100 text-gray-700 px-6 sm:px-8 py-4 rounded-xl text-base sm:text-lg font-semibold hover:bg-gray-200 transition min-h-[48px] flex items-center justify-center"
              >
                View Demo
              </Link>
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="bg-gray-50 py-20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="text-3xl md:text-4xl font-bold text-center text-gray-900 mb-16">
              Everything you need to close deals
            </h2>
            <div className="grid md:grid-cols-3 gap-8">
              {[
                {
                  icon: "🤖",
                  title: "AI-Generated Proposals",
                  desc: "Describe the job and get a complete proposal with scope, timeline, pricing, and terms — generated by GPT-4.",
                },
                {
                  icon: "🎨",
                  title: "Industry Templates",
                  desc: "Pre-built templates for contractors, landscapers, IT services, marketing agencies, cleaning services, and more.",
                },
                {
                  icon: "📄",
                  title: "PDF Export",
                  desc: "Download beautifully formatted PDF proposals with your branding to share with clients.",
                },
                {
                  icon: "🔗",
                  title: "Client Portal",
                  desc: "Share a secure link where clients can view, accept, or decline your proposal.",
                },
                {
                  icon: "✍️",
                  title: "E-Signatures",
                  desc: "Clients can sign proposals digitally right from the portal. No printing needed.",
                },
                {
                  icon: "📊",
                  title: "Analytics & Tracking",
                  desc: "Know when clients view your proposals, how long they spend, and when they make a decision.",
                },
              ].map((feature) => (
                <div
                  key={feature.title}
                  className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 hover:shadow-md transition"
                >
                  <div className="text-4xl mb-4">{feature.icon}</div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600">{feature.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Industries */}
        <section className="py-20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Built for service businesses
            </h2>
            <p className="text-gray-600 text-lg mb-12 max-w-2xl mx-auto">
              Pre-configured templates and AI fine-tuned for your industry
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              {["🏗️ General Contractor", "🌿 Landscaping", "✨ Cleaning", "💻 IT Services", "📈 Marketing", "💼 Consulting"].map(
                (industry) => (
                  <div
                    key={industry}
                    className="bg-gray-50 px-6 py-3 rounded-full text-gray-700 font-medium text-lg"
                  >
                    {industry}
                  </div>
                )
              )}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="bg-gradient-to-br from-blue-600 to-indigo-700 py-20">
          <div className="max-w-4xl mx-auto px-4 text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Ready to win more business?
            </h2>
            <p className="text-blue-100 text-lg mb-8">
              Start generating professional proposals in minutes. Free to try.
            </p>
            <Link
              href="/auth/signup"
              className="inline-block bg-white text-blue-600 px-8 py-4 rounded-xl text-lg font-semibold hover:bg-gray-50 transition"
            >
              Get Started Free →
            </Link>
          </div>
        </section>
      </main>

      <footer className="bg-gray-900 text-gray-400 py-12">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p>© 2025 ProposalPilot. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
